apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-auth
  namespace: kube-dev
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "false"
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: app-auth.yk.com
    http:
      paths:
      - path: /
        backend:
          serviceName: yk-auth
          servicePort: 9004
