apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: logging-kibana
  namespace: kube-system
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "false"
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: kibana.yk.com
    http:
      paths:
      - path: /
        backend:
          serviceName: kibana-logging
          servicePort: 5601
