---
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: yk-discovery
  namespace: kube-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yk-discovery
  template:
    metadata:
      name: yk-discovery
      labels:
        app: yk-discovery
      namespace: kube-dev
    spec:
      nodeSelector: 
        node: app
      containers:
      - name: yk-discovery
        imagePullPolicy: Always
        image: registry.cn-hangzhou.aliyuncs.com/yk-cloud/yk-discovery:latest
        ports:
        - name: server-port
          containerPort: 9001
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
      imagePullSecrets:
      - name: dev-sec
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: yk-discovery
  name: yk-discovery
  namespace: kube-dev
spec:
  type: ClusterIP
  ports:
  - port: 9001
    targetPort: 9001
  selector:
    app: yk-discovery
