---
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: yk-config
  namespace: kube-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yk-config
  template:
    metadata:
      name: yk-config
      labels:
        app: yk-config
      namespace: kube-dev
    spec:
      nodeSelector: 
        node: app    
      containers:
      - name: yk-config
        imagePullPolicy: Always
        image: registry.cn-hangzhou.aliyuncs.com/yk-cloud/yk-config:latest
        ports:
        - name: server-port
          containerPort: 9003
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
      imagePullSecrets:
      - name: dev-sec
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: yk-config
  name: yk-config
  namespace: kube-dev
spec:
  type: ClusterIP
  ports:
  - port: 9003
    targetPort: 9003
  selector:
    app: yk-config