kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: yk-demo-mgmt
  namespace: kube-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yk-demo-mgmt
  template:
    metadata:
      name: yk-demo-mgmt
      labels:
        app: yk-demo-mgmt
      namespace: kube-dev
    spec:
      nodeSelector: 
        node: app
      containers:
      - name: yk-demo-mgmt
        imagePullPolicy: Always
        image: registry.cn-hangzhou.aliyuncs.com/yk-cloud/yk-demo-mgmt:latest
        ports:
        - name: server-port
          containerPort: 9101
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
      imagePullSecrets:
      - name: dev-sec
